// Regenerates psl-rules.js from the Public Suffix List data shipped in the
// `psl` npm package (dev dependency). Run after bumping that package:
//   npm run update-psl

"use strict";

const fs = require("fs");
const path = require("path");
const { domainToASCII } = require("url");

const root = path.resolve(__dirname, "..");
const pkgDir = path.join(root, "node_modules", "psl"); // package "exports" hides its files
const { version } = JSON.parse(fs.readFileSync(path.join(pkgDir, "package.json"), "utf8"));
const source = fs.readFileSync(path.join(pkgDir, "data", "rules.js"), "utf8");
const rules = JSON.parse(source.replace(/^\s*export default\s*/, "").replace(/;\s*$/, ""));

// Hostnames from URL() are punycode, so the rules must be too
const ascii = [];
for (const rule of rules) {
  const prefix = rule.startsWith("!") ? "!" : rule.startsWith("*.") ? "*." : "";
  const body = domainToASCII(rule.slice(prefix.length));
  if (body) ascii.push(prefix + body);
}

const out = `// Generated by scripts/update-psl.js from psl@${version}. Do not edit.
//
// Public Suffix List data: This Source Code Form is subject to the terms of
// the Mozilla Public License, v. 2.0. If a copy of the MPL was not
// distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
// https://publicsuffix.org/

"use strict";

(function (root) {
  const rules = ${JSON.stringify(ascii.join(" "))};
  root.IDGAC_PSL_RULES = rules;
  if (typeof module === "object" && module.exports) module.exports = rules;
})(typeof globalThis !== "undefined" ? globalThis : this);
`;
fs.writeFileSync(path.join(root, "psl-rules.js"), out);
console.log(`psl-rules.js: ${ascii.length} rules from psl@${version} (${out.length} bytes)`);
